name: CI Build Steps [called]
on:
  workflow_call:
    secrets:
      TEST_TENANT_ID:
        required: true
      TEST_REGION:
        required: true
      TEST_OAUTH_CLIENT_SECRET:
        required: true
      TEST_OAUTH_CLIENT_ID:
        required: true
      TEST_API_KEY:
        required: true
  push:
    branches:
      - "*"

jobs:

  execute-pylint:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        pver:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    container: python:${{ matrix.pver }}
    steps:
      - name: Fetch Code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b

      - name: Make virtual environment
        shell: bash
        run: |
          pip install virtualenv
          virtualenv .venv
          . .venv/bin/activate
          
          pip install . pylint

      - name: Install packages
        shell: bash
        run: |
          pip install . pylint
  

      - name: Pylint
        shell: bash
        run: |
          pylint --disable=all --enable=E,F --disable=E1121 --score=false cxone_sarif


  call-package-build:
    uses: ./.github/workflows/build.yml
    with:
      buildonly: true
