name: Publish a Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version tag to use in the form of x.x.x"
        required: true
        type: string
      prerelease:
        description: "Check if this is to publish a pre-release."
        required: true
        type: boolean

permissions:
  contents: read

jobs:
  make-tag-string:
    runs-on: cx-public-ubuntu-x64
    outputs:
      tag: ${{ steps.tag-string.outputs.tag }}
    steps:
      - name: Create tag string
        run: |
          [ ${{ inputs.prerelease }} = false ] && echo "tag=${{ inputs.version }}" >> $GITHUB_OUTPUT || \
            echo "tag=${{ inputs.version }}rc$GITHUB_RUN_NUMBER" >> $GITHUB_OUTPUT
        id: tag-string

  validate-no-tag:
    runs-on: cx-public-ubuntu-x64
    needs: [make-tag-string]
    steps:
      - name: Fetch Code
        continue-on-error: true
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
        with:
          ref: refs/tags/${{ needs.make-tag-string.outputs.tag }}

      - name: Fail if tag ${{ needs.make-tag-string.outputs.tag }} exists
        run: |
          [[ $(git describe --tags) ==  ${{ needs.make-tag-string.outputs.tag }} ]] && exit 1 || :

  create-tag:
    runs-on: cx-public-ubuntu-x64
    permissions:
      contents: write
    needs: [make-tag-string, validate-no-tag]
    steps:
      - name: Fetch Code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
        
      - name: Set Version
        if: ${{ inputs.version != '' }}
        run: |
          git config --global user.email "${{ github.triggering_actor }}"
          git config --global user.name "${{ github.triggering_actor }}"
          git tag ${{ needs.make-tag-string.outputs.tag }}
          git push origin --tags

  # publish-release:
  #   permissions:
  #     contents: write
  #   needs: [make-tag-string, create-tag]
  #   uses: ./.github/workflows/build.yml
  #   with:
  #     version: ${{ needs.make-tag-string.outputs.tag }}
  #     prerelease: ${{ inputs.prerelease }}

  build-wheel:
    runs-on: cx-public-ubuntu-x64
    needs: [make-tag-string, create-tag]
    uses: ./.github/workflows/build-wheel.yml
    with:
      tag: ${{ needs.make-tag-string.outputs.tag }}
      prerelease: ${{ inputs.prerelease }}

  publish-release:
    runs-on: cx-public-ubuntu-x64
    needs: [make-tag-string, build-wheel]
    permissions:
      contents: write
    steps:
      - name: Placeholder
        run: exit 0

  artifact-cleanup:
    runs-on: cx-public-ubuntu-x64
    needs: [publish-release]
    if: always() && needs.build-wheel.result == 'success'
    steps:
      - uses: geekyeggo/delete-artifact@176a747ab7e287e3ff4787bf8a148716375ca118
        with:
          name: wheel-${{ github.run_number }}

  remove-tag-on-failure:
    needs: [make-tag-string, create-tag, publish-release]
    runs-on: cx-public-ubuntu-x64
    permissions:
      contents: write
    if: ${{ (failure() || cancelled()) && needs.create-tag.result == 'success' }}
    steps:
      - name: Fetch Code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b

      - name: Remove CodeTag
        run: git push origin ':refs/tags/${{ needs.make-tag-string.outputs.tag }}'
